import faker from 'faker';
import { defaultPostfix, getApiAddress } from '../../../../tests/shared';
import { CONFIG } from '../../../shared/config';
import { PostgreSqlService } from '../../../services/postgreSql';
import { gotInstance } from '../api.int.spec';
import { expect } from 'chai';


describe('PgSQL Contacts', () => {
    let tempDocId: string;
    const entitiyId = `entity-${defaultPostfix}`;
    const contactEmail = 'integration-test.contact@mail.com';
    const url = getApiAddress(CONFIG.API.ports.public);


    before(async () => {

        await PostgreSqlService.adapter.query(
            `INSERT INTO entities(
                name
                ,description
                ,data
                ,guid
            )
            VALUES (
                '${ entitiyId }'
                ,'autogenerated-by-integration-test'
                ,NULL
                ,'${ entitiyId }'
            )
        `);

        await PostgreSqlService.adapter.query(
            `INSERT INTO contacts(
                contact_id
                ,entity_id
                ,message_id
                ,data
            )
            VALUES (
                '${ contactEmail }'
                ,'${ entitiyId }'
                ,'${ faker.random.number(100000) }'
                ,'${ JSON.stringify({ email: contactEmail }) }'
            )
        `);

    });

    it('POST /v3/entities/<id>/contacts', async () => {

        const payload = {
            contact_id: 'test.contact@gmail.com',
            message_id: '123',
            data: {
                email: contactEmail
            }
        };

        const { statusCode, body: { ok } } = await gotInstance.post(`${ url }/v3/entities/${ entitiyId }/contacts`, {
            responseType: 'json',
            json: payload
        });

        expect(ok).to.be.true;

        const { rows } = await PostgreSqlService.adapter.query(
            `SELECT * FROM contacts
            WHERE entity_id = '${ entitiyId }';`
        );

        expect(rows).to.have.length.above(0);

    });

    it('GET /v3/contacts/<id>/entities', async () => {
        const { body: { ok, data } } = await gotInstance.get(`${ url }/v3/contacts/${ contactEmail }/entities`, {
            responseType: 'json'
        });

        expect(ok).to.be.true;
        expect(data).not.to.be.undefined;
        expect(data).to.have.length.above(0);

        const { rows } = await PostgreSqlService.adapter.query(
            `SELECT * FROM contacts
            WHERE entity_id = '${ entitiyId }';`
        );

        expect(rows).to.have.length.above(0);

    });


    after(async () => {

        await PostgreSqlService.adapter.query(
            `DELETE FROM contacts
            WHERE entity_id = '${ entitiyId }';`
        );

        await PostgreSqlService.adapter.query(
            `DELETE FROM entities
            WHERE name = '${ entitiyId }';`
        );

    });

});