import faker from 'faker';
import { gotInstance } from './integration.test';
import { expect } from 'chai';
import { PostgreSqlService } from '../../../src/services/postgreSql';


describe('PgSQL Contacts', () => {
    let tempDocId: string;
    const entitiyId = 'entity-integration-test';
    const contactEmail = 'integration-test.contact@mail.com';
    const url = 'https://localhost:3034';

    before(async () => {
        await PostgreSqlService.adapter.query(
            `INSERT INTO entities(
                name
                ,description
                ,data
                ,guid
            )
            VALUES (
                '${entitiyId}'
                ,'autogenerated-by-integration-test'
                ,NULL
                ,'${entitiyId}'
            )
        `);

        await PostgreSqlService.adapter.query(
            `INSERT INTO contacts(
                contact_id
                ,entity_id
                ,message_id
                ,data
            )
            VALUES (
                '${contactEmail}'
                ,'${entitiyId}'
                ,'${faker.random.number(100000)}'
                ,'${JSON.stringify({ email: contactEmail })}'
            )
        `);
    });

    it('POST /v3/entities/<id>/contacts', async () => {
        const payload = {
            contact_id: 'test.contact@gmail.com',
            message_id: '123',
            data: {
                email: contactEmail
            }
        };

        const { statusCode, body: { ok } } = await gotInstance.post(`${url}/v3/entities/${entitiyId}/contacts`, {
            responseType: 'json',
            json: payload
        });

        expect(ok).to.be.true;

        const { rows } = await PostgreSqlService.adapter.query(
            `SELECT * FROM contacts
            WHERE entity_id = '${entitiyId}';`
        );

        expect(rows).to.have.length.above(0);
    });

    it('GET /v3/contacts/<id>/entities', async () => {
        const { body } = await gotInstance.get(`${url}/v3/contacts/${contactEmail}/entities`, {
            responseType: 'json'
        });

        expect(body).to.be.not.undefined;
        expect(body).to.have.length.above(0);

        const { rows } = await PostgreSqlService.adapter.query(
            `SELECT * FROM contacts
            WHERE entity_id = '${entitiyId}';`
        );

        expect(rows).to.have.length.above(0);
    });


    after(async () => {

        await PostgreSqlService.adapter.query(
            `DELETE FROM contacts
            WHERE entity_id = '${entitiyId}';`
        );

        await PostgreSqlService.adapter.query(
            `DELETE FROM entities
            WHERE name = '${entitiyId}';`
        );

    });

});